[BREAKING] feat: stop supporting node <= 8
node-modules/byte pull request #35
Opened 2018-05-15 08:50 UTC by gxcsoccer

2018-05-15 14:32 UTC, fengmk2 commented
@gxcsoccer please change your commit author

![image](https://user-images.githubusercontent.com/156269/40063408-d2f78bf0-588f-11e8-83dc-a0c5ce7ee072.png)

2018-05-15 14:36 UTC, fengmk2 commented on lib/byte.js
> +  ByteBuffer.prototype[putMethod] = function(index, value) {
use `class` style instead of prototype?

2018-05-15 14:36 UTC, fengmk2 approved these changes

2018-05-15 14:38 UTC, fengmk2 commented
need to fixed package.json too https://github.com/node-modules/byte/blob/master/package.json#L55

2018-05-15 14:38 UTC, fengmk2 requested changes
ignore me

2018-05-15 14:39 UTC, fengmk2 approved these changes

2018-05-16 03:15 UTC, merged

2018-05-16 03:19 UTC, gxcsoccer commented
2.0.0